### ISSUE TITLE
Can the present master branch be used as an update for 2.0 and Phantom Liberty ?

### ISSUE THREAD

**Issue by Rool-IO** [Limai9999/Cyberpunk-2077-DualSense-Support#1]
Can we use the changes you made a week ago to update your mod for 2.0 and the Phantom Liberty expansion or should we wait for you to update and republish it on Nexusmods ?

**Comment by Limai9999** [comment]
No, it’s not updated for 2.0.
I’m working on update for 2.0 right now and will publish new version soon.

Сб, 30 сент. 2023 г. в 22:49, Rool-IO ***@***.***>:

**Comment by Rool-IO** [comment]
Preem ! Looking forward to it then. Closing the gig ;)
